# Generated by Django 4.2.28 on 2026-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_populate_mssql-technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='binary_path',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='binary_paths',
            field=models.JSONField(default=dict),
        ),
    ]
