# Generated by Django 5.2.12 on 2026-07-06 11:53

from django.db import migrations


def clear_erd_layouts(apps, schema_editor):
    ERDLayout = apps.get_model("app", "ERDLayout")
    ERDLayout.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_userdetails_binary_path_and_more'),
    ]

    operations = [
        migrations.RunPython(
            clear_erd_layouts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
